### ISSUE TITLE
Essentials - Unworking warp signs

### ISSUE THREAD

**Issue by RemiRiu95** [TheKinrar/Papyrus#23]
Nothing is happening when clicking on an Essentials [Warp] sign. Tested on Paper 1.14.4 - 209

**Comment by TheKinrar** [comment]
This is because Essentials, in https://github.com/EssentialsX/Essentials/blob/882699919e8decccf0f3cb078c8612cebc8354a7/Essentials/src/com/earth2me/essentials/utils/MaterialUtil.java, uses this method https://github.com/EssentialsX/Essentials/blob/882699919e8decccf0f3cb078c8612cebc8354a7/Essentials/src/com/earth2me/essentials/utils/EnumUtil.java#L23 (and another one below) to get Material fields via reflection and calls `isEnumConstant()` on them, which returns false.

**New compatibility layer is needed, intercepting calls to reflection API on some Class and Field methods.**
